---
title: "Research"
format: html
css: styles.css
---


In the _capacitated facility location problem with customer preferences (CFLP-CP)_, we are given a set of customers and potential facility locations. Each customer is associated with a demand, each facility is associated with a capacity and opening costs. Serving a customer at a facility incurs certain cost, and we assume that each customer has individual preferences regarding the facilities they want to be served at. The goal is to open facilities and assign customers so that each customer is served at their most preferred open facility, the capacity of each open facility is respected, and the total cost of opening facilities and assigning customers is minimised.
Real-world applications are, for example, the location of preventive care facilities.

##

#### Computational complexity

In a joint project with Christina Büsing and Timo Gersing, we study combinatorial structures of the CFLP-CP. While the problem's strong NP-completeness is expected, we observe that the structure of the customer preferences has an important impact on the problem's complexity.
If each customer has a strict preference order, the problem's feasibility can be determined in polynomial time. Determining optimality, however, is NP-hard as we prove via a reduction from vertex cover.
If preferences are defined by assignment costs, the problem can be solved in polynomial time if assignment costs are defined on a path.


- 
:::{.tight-spacing2}
  [Insights into the computational complexity of the single source capacitated facility location problem with customer preferences.](https://optimization-online.org/wp-content/uploads/2024/12/OO___EPLPO.pdf)

  C. Büsing, T. Gersing, S. Wrede.
  _Preprint submitted (2025)._
:::
- 
:::{.tight-spacing2}
  [Analysing the complexity of facility location problems with capacities, revenues, and closest assignments](https://openproceedings.org/2022/conf/inoc/INOC_2022_paper_22.pdf)
  
  C. Büsing, T. Gersing, S. Wrede.
  _INOC open proceedings (2022)_
:::


##
##

#### Exact methods
Together with Christina Büsing and Markus Leitner, we study preprocessing and valid inequalities to improve *Gurobi*'s performance when solving the CFLP-CP.
Our inequalities utilise information provided by the customer preferences. For example, if a set of customers forms a cover of a facility $j$, i.e., at least one customer must not be served at $j$ due to capacity restrictions, we know that any of these customers has to be served either at $j$ or at a facility they prefer over $j$. 
We formulate this observation as an inequality and further strengthen it.
We observe a positive impact of our preprocessing and inequalities in a computational study, especially if preferences are defined by assignment costs.


Together with Christina Büsing and Felix Engelhardt, we study a combinatorial branch-and-bound algorithm for the CFLP-CP with strict preference ordering, for which a feasible solution can be determined in polynomial time. 
The difficulty lies in obtaining strong dual bounds.
Here, we follow two approaches: 
In the first approach, we use a Lagrangian relaxation of the problem's IP formulation and solve it combinatorially. 
In the second approach, we solve an instance of a minimum-cost-flow problem which gives us a lower bound on combined assignment and opening costs. 
Core elements of our algorithm are domain propagation of the branching decisions, which are made on the location decisions, and a custom variable selection strategy based on search space reduction.
Our algorithm serves as a reliable alternative to *Gurobi* if RAM is limited, outperforming it for larger instances consisting of many ($500+$) customers and potential facility locations, respectively.


- 
:::{.tight-spacing2}
  [A combinatorial branch-and-bound algorithm for the capacitated facility location problem under strict customer preferences](https://optimization-online.org/?p=32480)

  C. Büsing, F. Engelhardt, S. Wrede.
  _Preprint (2025)._ 
:::
-
:::{.tight-spacing2}
  [Cover-based inequalities for the single-source capacitated facility location problem with customer preferences.](https://publications.rwth-aachen.de/record/1010742/files/1010742.pdf)

  C. Büsing, M. Leitner, S. Wrede.
  _Computers and Operations Research (2025)._
:::